config/routes.rb
Rails.application.routes.draw do
  root                  'static_pages#home'

  get 'home'        =>      'static_pages#home'
  get 'about'       =>      'static_pages#about'
  get 'contact'     =>      'static_pages#contact'
  get 'blog'        =>      'static_pages#blog'
  get 'portfolio'   =>      'static_pages#portfolio'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "igorrmotta"

    if (page_title.empty?)
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Home", home_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Portfolio", portfolio_path %></li>
      <li><%= link_to "Blog", blog_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "Blog", blog_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/blog.html.erb
<h1>StaticPages#blog</h1>
<p>Find me in app/views/static_pages/blog.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to Igor's Portfolio</h1>
</div>
<%= link_to image_tag("rails.png", alt: "rails logo"), 'http://rubyonrails.org' %>

app/views/static_pages/portfolio.html.erb
<h1>StaticPages#portfolio</h1>
<p>Find me in app/views/static_pages/portfolio.html.erb</p>